#ifndef MACROS_H_
#define MACROS_H_

#define ARGUMENT_INDEX_X_RES    0
#define ARGUMENT_INDEX_Y_RES    1
#define ARGUMENT_INDEX_FOV      2

#define ARGUMENT_INDEX_O_BUFFER 3
#define ARGUMENT_INDEX_TXT_M    4
#define ARGUMENT_INDEX_NML_M    5

#define ARGUMENT_INDEX_NB_TRI   6
#define ARGUMENT_INDEX_TRIS     7
#define ARGUMENT_INDEX_MATERIAL 8
#define ARGUMENT_INDEX_SKY_DIR  9
#define ARGUMENT_INDEX_NB_LIGHT 10
#define ARGUMENT_INDEX_LIGHTS   11

#define ARGUMENT_INDEX_CAM_POS  12
#define ARGUMENT_INDEX_CAM_DIR  13

#define ARGUMENT_INDEX_RD_SEED  14
#define ARGUMENT_INDEX_IT_COUNT 15


#endif //MACROS_H_